chore: update to new multiformats
libp2p/js-peer-id pull request #149
Opened 2021-06-02 08:05 UTC by achingbrain

Replaces multihashes with the new multiformats module

BREAKING CHANGE: uses the CID class from the new multiformats module

2021-06-02 15:07 UTC, achingbrain commented on src/index.js
> +const IDENTITY_CODE = 0x00
I think one of the design goals behind the new `multiformats` module was to not have the big lookup tables that `multicodec` is the guardian of.

2021-06-02 15:09 UTC, vasco-santos commented on src/index.js
> +const IDENTITY_CODE = 0x00
Fair enough. Probably worth adding a reference to the table just to reference where they come from? Probably to https://github.com/multiformats/multicodec/blob/master/table.csv

2021-06-02 15:20 UTC, achingbrain commented on src/index.js
> +const IDENTITY_CODE = 0x00
In my journey through the codebase doing the multiformats stuff it seems that we only really use four or five of them.  I think the only weirdness is when bitswap has to [mess around with CID prefixes](https://github.com/ipfs/js-ipfs-bitswap/blob/58a8de1f4ffb8311bbbbe066e6a869df1d2bc4c0/src/types/message/index.js#L280) in incoming bitswap 1.1.0 messages.

2021-06-02 15:51 UTC, vasco-santos commented on src/index.js
> +const IDENTITY_CODE = 0x00
I think just adding a comment above with the multicodec table is enough here

2021-06-03 10:10 UTC, achingbrain commented on src/index.js
> +const IDENTITY_CODE = 0x00
Done!

2021-06-03 12:18 UTC, vasco-santos approved these changes
LGTM! Let me know when I should release it

2021-06-03 17:33 UTC, achingbrain commented
I've tightened up the input types for `PeerId.createFromCID` as a follow on from https://github.com/multiformats/js-multiformats/pull/91#issuecomment-853762442 - it now only takes `CID` instances.

2021-06-04 13:43 UTC, vasco-santos approved these changes
👌🏼

2021-06-23 09:31 UTC, vasco-santos commented
@achingbrain FYI #150 should also be ready soon (also breaking change), so I would like to get these shipped together as bubbling up PeerId updates across all libp2p stack is time consuming. This will create some conflicts that will need to be addresses by the second PR to be merged

2021-07-06 11:15 UTC, vasco-santos requested changes
Can you also have the README updated for `parse` and `createFromCID`?

2021-07-06 11:15 UTC, vasco-santos commented on src/index.d.ts
> +   * @param buf Protobuf bytes, as Uint8Array or hex-encoded string.
```suggestion
   * @param str encoded public key string.
```

2021-07-06 12:27 UTC, vasco-santos approved these changes

2021-07-06 12:27 UTC, merged